require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DisponibilitesController do

  # This should return the minimal set of attributes required to create a valid
  # Disponibilite. As you add validations to Disponibilite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "utilisateur_absent_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DisponibilitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all disponibilites as @disponibilites" do
      disponibilite = FactoryGirl.create(:disponibilite_disponible)
      get :index, {}, valid_session
      assigns(:disponibilites).should eq([disponibilite])
    end
  end

  describe "GET show" do
    it "assigns the requested disponibilite as @disponibilite" do
      disponibilite = FactoryGirl.create(:disponibilite_disponible)
      get :show, {:id => disponibilite.to_param}, valid_session
      assigns(:disponibilite).should eq(disponibilite)
    end
  end

  describe "GET new" do
    it "assigns a new disponibilite as @disponibilite" do
      utilisateur_absent = FactoryGirl.create(:utilisateur_permanent)
      Utilisateur.stub_chain(:where, :all).and_return(utilisateur_absent)
      get :new, {}, valid_session
      assigns(:disponibilite).should be_a_new(Disponibilite)
    end

    it "aucun utilisateur absent disponible" do
      Utilisateur.stub_chain(:where, :all).and_return(nil)
      get :new, {}, valid_session
      response.should redirect_to(disponibilites_url)
    end
  end

  describe "GET edit" do
    it "assigns the requested disponibilite as @disponibilite" do
      disponibilite = FactoryGirl.create(:disponibilite_disponible)
      get :edit, {:id => disponibilite.to_param}, valid_session
      assigns(:disponibilite).should eq(disponibilite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      describe "with utilisateur_absent" do
        before(:each) do
          utilisateur_absent = FactoryGirl.create(:utilisateur_permanent)
          Utilisateur.stub_chain(:where, :all).and_return(utilisateur_absent)

          @utilisateur_remplacant = FactoryGirl.create(:utilisateur_remplacant)
          Utilisateur.stub_chain(:order, :joins, :where, :first).and_return(@utilisateur_remplacant)
        end

        it "creates a new Disponibilite" do
          expect {
            post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "attente", "utilisateur_absent_id" => "11", "utilisateur_remplacant_id" => @utilisateur_remplacant.id}}, valid_session
          }.to change(Disponibilite, :count).by(1)
        end

        it "assigns a newly created disponibilite as @disponibilite" do
          post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "attente", "utilisateur_absent_id" => "11", "utilisateur_remplacant_id" => @utilisateur_remplacant.id}}, valid_session
          assigns(:disponibilite).should be_a(Disponibilite)
          assigns(:disponibilite).should be_persisted
        end

        it "redirects to the created disponibilite" do
          post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "attente", "utilisateur_absent_id" => "11", "utilisateur_remplacant_id" => @utilisateur_remplacant.id}}, valid_session
          response.should redirect_to(Disponibilite.last)
        end
      end

      describe "without utilisateur_absent" do
        before(:each) do
          utilisateur_absent = FactoryGirl.create(:utilisateur_permanent)
          Utilisateur.stub_chain(:where, :all).and_return(utilisateur_absent)

          @utilisateur_remplacant = FactoryGirl.create(:utilisateur_remplacant)
          Utilisateur.stub_chain(:order, :joins, :where, :first).and_return(nil)
        end

        it "creates a new Disponibilite" do
          expect {
            post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "disponible", "utilisateur_absent_id" => "11", "utilisateur_remplacant_id" => nil}}, valid_session
          }.to change(Disponibilite, :count).by(1)
        end

        it "assigns a newly created disponibilite as @disponibilite" do
          post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "disponible", "utilisateur_absent_id" => "11", "utilisateur_remplacant_id" => nil}}, valid_session
          assigns(:disponibilite).should be_a(Disponibilite)
          assigns(:disponibilite).should be_persisted
        end

        it "redirects to the created disponibilite" do
          post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "disponible", "utilisateur_absent_id" => "11", "utilisateur_remplacant_id" => nil}}, valid_session
          response.should redirect_to(Disponibilite.last)
        end
      end

      #it "utilisateur remplacant" do
      #  post :create, {disponibilite: {"endroit_id" => "11", "niveau_id" => "12", "date_heure_debut" => DateTime.now + 1.minute, "date_heure_fin" => DateTime.now + 1.hour, "statut" => "disponible", "utilisateur_absent_id" => "11"}}, valid_session
      #  assigns(disponibilite.utilisateur_remplacant).should equal(utilisateur_remplacant)
      #end
    end

    describe "with invalid params" do
      before(:each) do
        utilisateur_absent = FactoryGirl.create(:utilisateur_permanent)
        Utilisateur.stub_chain(:where, :all).and_return(utilisateur_absent)

        utilisateur_remplacant = FactoryGirl.create(:utilisateur_remplacant)
        Utilisateur.stub_chain(:order, :joins, :where, :first).and_return(utilisateur_remplacant)
      end

      it "assigns a newly created but unsaved disponibilite as @disponibilite" do
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        post :create, {:disponibilite => { "utilisateur_absent_id" => "invalid value" }}, valid_session
        assigns(:disponibilite).should be_a_new(Disponibilite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        post :create, {:disponibilite => { "utilisateur_absent_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested disponibilite" do
        disponibilite = FactoryGirl.create(:disponibilite_disponible)
        # Assuming there are no other disponibilites in the database, this
        # specifies that the Disponibilite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Disponibilite.any_instance.should_receive(:update).with({ "utilisateur_absent_id" => "1" })
        put :update, {:id => disponibilite.to_param, :disponibilite => { "utilisateur_absent_id" => "1" }}, valid_session
      end

      it "assigns the requested disponibilite as @disponibilite" do
        disponibilite = FactoryGirl.create(:disponibilite_disponible)
        put :update, {:id => disponibilite.to_param, :disponibilite => valid_attributes}, valid_session
        assigns(:disponibilite).should eq(disponibilite)
      end

      it "redirects to the disponibilite" do
        disponibilite = FactoryGirl.create(:disponibilite_disponible)
        put :update, {:id => disponibilite.to_param, :disponibilite => valid_attributes}, valid_session
        response.should redirect_to(disponibilite)
      end
    end

    describe "with invalid params" do
      it "assigns the disponibilite as @disponibilite" do
        disponibilite = FactoryGirl.create(:disponibilite_disponible)
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        put :update, {:id => disponibilite.to_param, :disponibilite => { "utilisateur_absent_id" => "invalid value" }}, valid_session
        assigns(:disponibilite).should eq(disponibilite)
      end

      it "re-renders the 'edit' template" do
        disponibilite = FactoryGirl.create(:disponibilite_disponible)
        # Trigger the behavior that occurs when invalid params are submitted
        Disponibilite.any_instance.stub(:save).and_return(false)
        put :update, {:id => disponibilite.to_param, :disponibilite => { "utilisateur_absent_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested disponibilite" do
      disponibilite = FactoryGirl.create(:disponibilite_disponible)
      expect {
        delete :destroy, {:id => disponibilite.to_param}, valid_session
      }.to change(Disponibilite, :count).by(-1)
    end

    it "redirects to the disponibilites list" do
      disponibilite = FactoryGirl.create(:disponibilite_disponible)
      delete :destroy, {:id => disponibilite.to_param}, valid_session
      response.should redirect_to(disponibilites_url)
    end
  end
end
