require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EcolesController do

  # This should return the minimal set of attributes required to create a valid
  # Ecole. As you add validations to Ecole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nom" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EcolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ecoles as @ecoles" do
      ecole = Ecole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ecoles).should eq([ecole])
    end
  end

  describe "GET show" do
    it "assigns the requested ecole as @ecole" do
      ecole = Ecole.create! valid_attributes
      get :show, {:id => ecole.to_param}, valid_session
      assigns(:ecole).should eq(ecole)
    end
  end

  describe "GET new" do
    it "assigns a new ecole as @ecole" do
      get :new, {}, valid_session
      assigns(:ecole).should be_a_new(Ecole)
    end
  end

  describe "GET edit" do
    it "assigns the requested ecole as @ecole" do
      ecole = Ecole.create! valid_attributes
      get :edit, {:id => ecole.to_param}, valid_session
      assigns(:ecole).should eq(ecole)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ecole" do
        expect {
          post :create, {:ecole => valid_attributes}, valid_session
        }.to change(Ecole, :count).by(1)
      end

      it "assigns a newly created ecole as @ecole" do
        post :create, {:ecole => valid_attributes}, valid_session
        assigns(:ecole).should be_a(Ecole)
        assigns(:ecole).should be_persisted
      end

      it "redirects to the created ecole" do
        post :create, {:ecole => valid_attributes}, valid_session
        response.should redirect_to(Ecole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ecole as @ecole" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ecole.any_instance.stub(:save).and_return(false)
        post :create, {:ecole => { "nom" => "invalid value" }}, valid_session
        assigns(:ecole).should be_a_new(Ecole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ecole.any_instance.stub(:save).and_return(false)
        post :create, {:ecole => { "nom" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ecole" do
        ecole = Ecole.create! valid_attributes
        # Assuming there are no other ecoles in the database, this
        # specifies that the ecole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ecole.any_instance.should_receive(:update).with({ "nom" => "MyString" })
        put :update, {:id => ecole.to_param, :ecole => { "nom" => "MyString" }}, valid_session
      end

      it "assigns the requested ecole as @ecole" do
        ecole = Ecole.create! valid_attributes
        put :update, {:id => ecole.to_param, :ecole => valid_attributes}, valid_session
        assigns(:ecole).should eq(ecole)
      end

      it "redirects to the ecole" do
        ecole = Ecole.create! valid_attributes
        put :update, {:id => ecole.to_param, :ecole => valid_attributes}, valid_session
        response.should redirect_to(ecole)
      end
    end

    describe "with invalid params" do
      it "assigns the ecole as @ecole" do
        ecole = Ecole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ecole.any_instance.stub(:save).and_return(false)
        put :update, {:id => ecole.to_param, :ecole => { "nom" => "invalid value" }}, valid_session
        assigns(:ecole).should eq(ecole)
      end

      it "re-renders the 'edit' template" do
        ecole = Ecole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ecole.any_instance.stub(:save).and_return(false)
        put :update, {:id => ecole.to_param, :ecole => { "nom" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ecole" do
      ecole = Ecole.create! valid_attributes
      expect {
        delete :destroy, {:id => ecole.to_param}, valid_session
      }.to change(Ecole, :count).by(-1)
    end

    it "redirects to the ecoles list" do
      ecole = Ecole.create! valid_attributes
      delete :destroy, {:id => ecole.to_param}, valid_session
      response.should redirect_to(ecoles_url)
    end
  end

end
