require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EndroitsController do

  # This should return the minimal set of attributes required to create a valid
  # Endroit. As you add validations to Endroit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nom" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EndroitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all endroits as @endroits" do
      endroit = Endroit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:endroits).should eq([endroit])
    end
  end

  describe "GET show" do
    it "assigns the requested endroit as @endroit" do
      endroit = Endroit.create! valid_attributes
      get :show, {:id => endroit.to_param}, valid_session
      assigns(:endroit).should eq(endroit)
    end
  end

  describe "GET new" do
    it "assigns a new endroit as @endroit" do
      get :new, {}, valid_session
      assigns(:endroit).should be_a_new(Endroit)
    end
  end

  describe "GET edit" do
    it "assigns the requested endroit as @endroit" do
      endroit = Endroit.create! valid_attributes
      get :edit, {:id => endroit.to_param}, valid_session
      assigns(:endroit).should eq(endroit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Endroit" do
        expect {
          post :create, {:endroit => valid_attributes}, valid_session
        }.to change(Endroit, :count).by(1)
      end

      it "assigns a newly created endroit as @endroit" do
        post :create, {:endroit => valid_attributes}, valid_session
        assigns(:endroit).should be_a(Endroit)
        assigns(:endroit).should be_persisted
      end

      it "redirects to the created endroit" do
        post :create, {:endroit => valid_attributes}, valid_session
        response.should redirect_to(Endroit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved endroit as @endroit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Endroit.any_instance.stub(:save).and_return(false)
        post :create, {:endroit => { "nom" => "invalid value" }}, valid_session
        assigns(:endroit).should be_a_new(Endroit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Endroit.any_instance.stub(:save).and_return(false)
        post :create, {:endroit => { "nom" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested endroit" do
        endroit = Endroit.create! valid_attributes
        # Assuming there are no other endroits in the database, this
        # specifies that the Endroit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Endroit.any_instance.should_receive(:update).with({ "nom" => "MyString" })
        put :update, {:id => endroit.to_param, :endroit => { "nom" => "MyString" }}, valid_session
      end

      it "assigns the requested endroit as @endroit" do
        endroit = Endroit.create! valid_attributes
        put :update, {:id => endroit.to_param, :endroit => valid_attributes}, valid_session
        assigns(:endroit).should eq(endroit)
      end

      it "redirects to the endroit" do
        endroit = Endroit.create! valid_attributes
        put :update, {:id => endroit.to_param, :endroit => valid_attributes}, valid_session
        response.should redirect_to(endroit)
      end
    end

    describe "with invalid params" do
      it "assigns the endroit as @endroit" do
        endroit = Endroit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Endroit.any_instance.stub(:save).and_return(false)
        put :update, {:id => endroit.to_param, :endroit => { "nom" => "invalid value" }}, valid_session
        assigns(:endroit).should eq(endroit)
      end

      it "re-renders the 'edit' template" do
        endroit = Endroit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Endroit.any_instance.stub(:save).and_return(false)
        put :update, {:id => endroit.to_param, :endroit => { "nom" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested endroit" do
      endroit = Endroit.create! valid_attributes
      expect {
        delete :destroy, {:id => endroit.to_param}, valid_session
      }.to change(Endroit, :count).by(-1)
    end

    it "redirects to the endroits list" do
      endroit = Endroit.create! valid_attributes
      delete :destroy, {:id => endroit.to_param}, valid_session
      response.should redirect_to(endroits_url)
    end
  end

end
