require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UtilisateursController do

  # This should return the minimal set of attributes required to create a valid
  # Utilisateur. As you add validations to Utilisateur, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "utilisateur@courriel.ca", "nom" => "Nom", "prenom" => "Prénom", "numero_telephone" => "444 444-4444", "titre" => "Permanent", "password" => "12345678" } }
  let(:valid_attributes_without_password) { { "email" => "utilisateur@courriel.ca", "nom" => "Nom", "prenom" => "Prénom", "numero_telephone" => "444 444-4444", "titre" => "Permanent" } }

  describe "GET index" do
    describe "valid session" do
      it "assigns all utilisateurs as @utilisateurs" do
        utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        utilisateur.roles= [role]

        sign_in utilisateur

        Utilisateur.stub_chain(:where, :first).and_return(utilisateur)

        allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

        utilisateur_permanent = FactoryGirl.create(:utilisateur_permanent2)

        allow(Utilisateur).to receive(:all) {[utilisateur_permanent]}

        get :index, {}
        assigns(:utilisateurs).should eq([utilisateur_permanent])
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})

      get :index, {}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end

  describe "GET show" do
    describe "valid session" do
      it "assigns the requested utilisateur as @utilisateur" do
        utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        utilisateur.roles= [role]

        sign_in utilisateur

        Utilisateur.stub_chain(:where, :first).and_return(utilisateur)

        allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

        allow(Utilisateur).to receive(:find).with(utilisateur.id.to_s) { utilisateur }

        utilisateur_permanent = FactoryGirl.create(:utilisateur_permanent2)

        allow(Utilisateur).to receive(:all) {[utilisateur_permanent]}

        get :show, {:id => utilisateur}
        assigns(:utilisateur).should eq(utilisateur)
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})

      utilisateur = create(:utilisateur_permanent)
      get :show, {:id => utilisateur}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end

  describe "GET new" do
    describe "valid session" do
      it "assigns a new utilisateur as @utilisateur" do
        utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        utilisateur.roles= [role]

        sign_in utilisateur

        Utilisateur.stub_chain(:where, :first).and_return(utilisateur)

        allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

        get :new, {}
        assigns(:utilisateur).should be_a_new(Utilisateur)
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})

      get :new, {}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end

  describe "GET edit" do
    describe "valid session" do
      it "assigns the requested utilisateur as @utilisateur" do
        utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        utilisateur.roles= [role]

        sign_in utilisateur

        Utilisateur.stub_chain(:where, :first).and_return(utilisateur)

        allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

        allow(Utilisateur).to receive(:find).with(utilisateur.id.to_s) { utilisateur }

        get :edit, {:id => utilisateur.to_param}
        assigns(:utilisateur).should eq(utilisateur)
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})
      utilisateur = create(:utilisateur_permanent)

      get :edit, {:id => utilisateur.to_param}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end

  describe "POST create" do
    describe "valid session" do
      before(:each) do
        @utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        @utilisateur.roles= [role]

        sign_in @utilisateur
      end

      describe "with valid params" do

        it "assigns a newly created utilisateur as @utilisateur" do
          utilisateur_permanent = create(:utilisateur_permanent2)
          allow(Utilisateur).to receive(:new) {utilisateur_permanent}

          allow(utilisateur_permanent).to receive(:save) {true}

          post :create, {:utilisateur => valid_attributes}
          assigns(:utilisateur).should be_a(Utilisateur)
          assigns(:utilisateur).should be_persisted
        end

        it "assigns a newly created utilisateur as @utilisateur without password" do
          utilisateur_permanent = create(:utilisateur_permanent2)
          utilisateur_permanent.password= nil

          allow(Utilisateur).to receive(:new) {utilisateur_permanent}

          allow(utilisateur_permanent).to receive(:save) {true}

          post :create, {:utilisateur => valid_attributes_without_password}
          assigns(:utilisateur).should be_a(Utilisateur)
          assigns(:utilisateur).should be_persisted
        end

        #it "redirects to the created utilisateur" do
        #  utilisateur = create(:utilisateur_permanent)
        #  Utilisateur.stub(:new).and_return(utilisateur)

        #  utilisateur.stub(:save).and_return(true)

        #  post :create, {:utilisateur => valid_attributes}
        #  response.should redirect_to(Utilisateur.last)
        #end
      end

      describe "with invalid params" do
        before(:each) do
          allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}
        end

        it "assigns a newly created but unsaved utilisateur as @utilisateur" do
          # Trigger the behavior that occurs when invalid params are submitted
          Utilisateur.any_instance.stub(:save).and_return(false)
          post :create, {:utilisateur => valid_attributes}
          assigns(:utilisateur).should be_a_new(Utilisateur)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Utilisateur.any_instance.stub(:save).and_return(false)
          post :create, {:utilisateur => valid_attributes}
          response.should render_template("new")
        end
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})

      post :create, {:utilisateur => valid_attributes}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end

  describe "PUT update" do
    describe "valid session" do
      before(:each) do
        @utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        @utilisateur.roles= [role]

        sign_in @utilisateur
      end

      describe "with valid params" do
        before(:each) do
          @utilisateur_permanent = create(:utilisateur_permanent2)
          allow(Utilisateur).to receive(:find).with(@utilisateur_permanent.id.to_s) {@utilisateur_permanent}
        end

        it "updates the requested utilisateur" do
          # Assuming there are no other utilisateurs in the database, this
          # specifies that the Utilisateur created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          Utilisateur.any_instance.should_receive(:update).with( valid_attributes).and_return(true)
          put :update, {:id => @utilisateur_permanent.to_param, :utilisateur => valid_attributes}
        end

        it "updates the requested utilisateur without password" do
          @utilisateur.password= nil
          # Assuming there are no other utilisateurs in the database, this
          # specifies that the Utilisateur created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          Utilisateur.any_instance.should_receive(:update).with( valid_attributes_without_password).and_return(true)
          put :update, {:id => @utilisateur_permanent.to_param, :utilisateur => valid_attributes_without_password}

        end

        it "assigns the requested utilisateur as @utilisateur" do
          put :update, {:id => @utilisateur_permanent.to_param, :utilisateur => valid_attributes}
          assigns(:utilisateur).should eq(@utilisateur_permanent)
        end

        it "redirects to the utilisateur" do
          put :update, {:id => @utilisateur_permanent.to_param, :utilisateur => valid_attributes}
          response.should redirect_to(@utilisateur_permanent)
        end
      end

      describe "with invalid params" do
        before(:each) do
          allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

          @utilisateur_permanent = create(:utilisateur_permanent2)
          allow(Utilisateur).to receive(:find).with(@utilisateur_permanent.id.to_s) {@utilisateur_permanent}
        end

        it "assigns the utilisateur as @utilisateur" do
          # Trigger the behavior that occurs when invalid params are submitted
          Utilisateur.any_instance.stub(:save).and_return(false)
          put :update, {:id => @utilisateur_permanent.to_param, :utilisateur => valid_attributes}
          assigns(:utilisateur).should eq(@utilisateur_permanent)
        end

        it "re-renders the 'edit' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Utilisateur.any_instance.stub(:save).and_return(false)
          put :update, {:id => @utilisateur_permanent.to_param, :utilisateur => valid_attributes}
          response.should render_template("edit")
        end
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})
      @utilisateur = create(:utilisateur_permanent)

      put :update, {:id => @utilisateur.to_param, :utilisateur => valid_attributes}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end

  describe "DELETE destroy" do
    describe "valid session" do
      before(:each) do
        @utilisateur = FactoryGirl.create(:utilisateur_admin)
        role = FactoryGirl.create(:role)
        @utilisateur.roles= [role]

        sign_in @utilisateur
      end

      #it "destroys the requested utilisateur" do
      #  expect {
      #    delete :destroy, {:id => @utilisateur.to_param}
      #  }.to change(Utilisateur, :count).by(-1)
      #end

      it "redirects to the utilisateurs list" do
        @utilisateur_permanent = create(:utilisateur_permanent2)
        allow(Utilisateur).to receive(:find).with(@utilisateur_permanent.id.to_s) {@utilisateur_permanent}

        allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

        delete :destroy, {:id => @utilisateur_permanent.to_param}
        response.should redirect_to(utilisateurs_url)
      end
    end
    it "invalid session" do
      allow(request.env['warden']).to receive(:authenticate!).and_throw(:warden, {:scope => :utilisateur})
      @utilisateur_permanent = create(:utilisateur_permanent2)

      allow(Disponibilite).to receive(:where).with("(statut = 'attente' or statut = 'disponible') and date_heure_debut between :date_debut and :date_fin",{date_debut: Date.current, :date_fin=> Date.current + 2.months}) {nil}

      delete :destroy, {:id => @utilisateur_permanent.to_param}

      response.should redirect_to(new_utilisateur_session_path)
    end
  end
end
